#!/bin/bash

# Set variables
CONTAINER_REPO_NAME=${TRAVIS_REPO_SLUG:-"train"}

if [ "${GIT_TAG}" == "master" ]; then
  CONTAINER_IMAGE_TAG="latest"
else
  CONTAINER_IMAGE_TAG="${GIT_TAG}"
fi

CONTAINER_IMAGE_NAME="${CONTAINER_REPO_NAME}:${CONTAINER_IMAGE_TAG}"

echo "CONTAINER_IMAGE_NAME: ${CONTAINER_IMAGE_NAME}"
